extends Node
class_name Gearmods

var deck = [
	{
		"type": "Mod",
		"buy": 2,
		"name": "targeting computer",
		"description": "Ship Combat:\n1 reroll per Blank",
		"patrol": "D",
		"move": 3,
	},
#	{
#		"type": "Mod",
#		"buy": 2,
#		"name": "quad laser",
#		"description": "Attack: +1S",
#		"patrol": "C",
#		"move": 3,
#	},
#	{
#		"type": "Mod",
#		"buy": 3,
#		"name": "nav computer",
#		"description": "Speed: +1",
#	},
#	{
#		"type": "Mod",
#		"buy": 3,
#		"name": "shield upgrade",
#		"description": "Armor: +1S\nAction: Recover 1 Ship Damage",
#	},
#	{
#		"type": "Mod",
#		"buy": 5,
#		"name": "maneuvering thrusters",
#		"description": "Armor: +1S\nShip Combat\nWith Tactics:\n-1 Enemy Attack",
#	},
#	{
#		"type": "Mod",
#		"buy": 5,
#		"name": "ion cannon",
#		"description": "Ship Combat:\n-1 Enemy Hit\nWith Tactics:\n-1 Enemy Crit",
#		"patrol": "A",
#		"move": 3,
#	},
#	{
#		"type": "Mod",
#		"buy": 7,
#		"name": "autoblaster",
#		"description": "Ship Combat:\n2 Focus to Hit\nWith Tactics:\n1 Focus to Crit",
#		"patrol": "B",
#		"move": 3,
#	},
#	{
#		"type": "Gear",
#		"buy": 3,
#		"name": "blaster pistol",
#		"description": "Attack: +1G",
#		"patrol": "B",
#		"move": 3,
#	},
	{
		"type": "Gear",
		"subtype": "Armor",
		"buy": 3,
		"name": "armored vest",
		"description": "Armor: +2G",
		"patrol": "C",
		"move": 3,
	},
#	{
#		"type": "Gear",
#		"buy": 4,
#		"name": "vibroknife",
#		"description": "Ground Combat:\n1 Focus to Hit\nWith Strength or Stealth: Attack +1",
#		"patrol": "B",
#		"move": 4,
#	},
#	{
#		"type": "Gear",
#		"buy": 5,
#		"name": "blaster rifle",
#		"description": "Attack: +1G\nWon Ground Combat:\nMax Damage: 2",
#		"patrol": "D",
#		"move": 4,
#	},
#	{
#		"type": "Gear",
#		"buy": 6,
#		"name": "vibroax",
#		"description": "Attack: +1G\nGround Combat\nWith Strength:\n1 Focus to Crit",
#		"patrol": "A",
#		"move": 3,
#	},
#	{
#		"type": "Gear",
#		"buy": 6,
#		"name": "jetpack",
#		"description": "Ground Combat:\n-1 Enemy Hit\nWith Tactics:\n-1 Enemy Crit",
#		"patrol": "A",
#		"move": 4,
#	},
#	{
#		"type": "Gear",
#		"buy": 8,
#		"name": "grenade",
#		"description": "Attack +2G",
#		"patrol": "D",
#		"move": 3,
#	},
	{
		"type": "Gear",
		"subtype": "Armor",
		"buy": 8,
		"name": "plastoid armor",
		"description": "Armor +2G\nGround Combat\nWith Strength:\n-1 Enemy Attack",
		"patrol": "C",
		"move": 4,
	},
]
